### PR TITLE
Unittest Integration

### LINKED ISSUE #12: Add method to generate cassette names from TestCase instances
`unittest` is probably still one of the most used testing libraries in Python (and it comes for free with any Python installation). If you write your tests anything like how I write my tests, the structure is similar to:

```python
import unittest


class TestCase(unittest.TestCase):
    def test_foo(self):
        print(self.id())


if __name__ == '__main__':
    unittest.main()
```

If you run the code above, you'll see:

```
__main__.TestCase.test_foo
.
----------------------------------------------------------------------
Ran 1 test in 0.002s

OK
```

(At least in python 2.7+, I still need to test this in python 2.6 although the [docs](http://docs.python.org/2.6/library/unittest.html?highlight=unittest#unittest.TestCase.id) indicate it should work)

We should at least provide a method on `Betamax` like `generate_cassette_name` which takes (at least) two optional arguments:

- `from_unittest`
- `from_function`

The former will take an instance of `unittest.TestCase`, (i.e., `self` in the example above) and the latter will take the function. You could then have:

```python
import requests
import betamax
import unittest


class TestHTTPBin(unittest.TestCase):
    def setUp(self):
        self.session = requests.Session()
        self.recorder = Betamax(self.session)
        self.cassette_name = self.recorder.generate_cassette_name(self)

    def test_get(self):
        with self.recorder.use_cassette(self.cassette_name):
            r = self.session.get('http://httpbin.org/get')
        assert r.status_code == 200


if __name__ == '__main__':
    unittest.main()
```

Even from within `setUp`, `self.id()` understands who the calling test function is. This example will create a cassette called `HTTPBin_test_get.json` is the cassette library. Similarly, functions (and methods) have a sense of identity and we can extract that using the second parameter.

```python
import requests
import betamax


def test_get():
    session = requests.Session()
    recorder = Betamax(session)
    cassette_name = recorder.generate_cassette_name(from_function=test_get)
    with recorder.use_cassette(cassette_name):
        r = session.get('http://httpbin.org/get')
    assert r.status_code == 200


if __name__ == '__main__':
    test_get()
```

This would generate a cassette called `test_get.json`.

### PR DESCRIPTION
**Pull request by sigmavirus24**
Closes #12

### CODE REVIEW

**Comment by sigmavirus24** [comment]
@Lukasa do you have any ideas on how one might go about testing this?

**Comment by Lukasa** [comment]
Where "this" is...Betamax?

**Comment by sigmavirus24** [comment]
This is BetamaxTestCase
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Lukasa** [comment]
Oh god. I have no idea how to unit test unittest integration. Um.

Maybe write some sample unit tests using it that exercise all the function?

**Comment by sigmavirus24** [comment]
See the kind of stuff I get myself into without you @Lukasa? =P

**Comment by Lukasa** [comment]
Yeah, but the flip side is: py.test fixtures!

**Comment by sigmavirus24** [comment]
I know, right?! That was a different PR though. =P

**Pull request merged**
